name: status_saver
description: "Open Source Status Saver application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.8.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^10.1.0
  saf: ^1.0.3+4
  flutter_staggered_grid_view: ^0.7.0
  appcheck: ^1.1.0
  chewie: ^1.8.1
  photo_view: ^0.15.0
  video_thumbnail: ^0.5.3
  video_player: ^2.8.7
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true